### ISSUE TITLE
Local variable restartMenuOption not initialized

### ISSUE THREAD

**Issue by jgedri** [RichardBray/Scales-A-Pangolin-Story#9]
Looks like a variable in PauseMenu.hx isn't initiated.
`? _standardMenuItems.concat(restartMenuOption)`

**Comment by RichardBray** [comment]
Thanks for checking @jgedri I feel like it's initiated here:
https://github.com/RichardBray/Scales-A-Pangolin-Story/blob/master/source/PauseMenu.hx#L89

But I could be wrong.
